name: BuildAndDepploy
on: 
  pull_request: 
    types: 
      - opened
  push: 
    branches: 
      - main
      - feat/**
  workflow_dispatch:
env:
  myscretkey: ${{secrets.MYSECRETKEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
         name: artifact
         path: dist
      - name: version generation
        id: publish 
        run: echo version=27.1.5 >> $GITHUB_OUTPUT
      - name: echo secret
        run: echo ${{env.myscretkey}}
      - name: Build
        run: echo "Build done" 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
         name: artifact
      - name: List content
        run: ls
      - name: Github context
        run: echo "${{toJson(github)}}"
      - name: version echo
        run: echo ${{needs.build.outputs.version}}
      - name: Deploy
        run: echo "Deploy done" 