name: BuildAndDepploy
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: run test
        run: npm tests
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Something" 