name: BuildAndDepploy
on: 
  pull_request: 
    types: 
      - opened
  push: 
    branches: 
      - main
      - feat/**
    paths:
      - src/components/HelpArea.css
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Build
        run: echo "Build done" 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Github context
        run: echo "${{toJson(github)}}"
      - name: Deploy
        run: echo "Deploy done" 